# Generated by Django 2.0.6 on 2018-07-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='features_heading',
            field=models.CharField(default='Почему мы?', max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
