# Generated by Django 2.0.6 on 2018-07-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180713_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='feature_1_text',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium, magni?', max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='feature_2_text',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium, magni?', max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='feature_3_text',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium, magni?', max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='feature_4_text',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium, magni?', max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='feature_5_text',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium, magni?', max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='feature_6_text',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium, magni?', max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='feature_7_text',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium, magni?', max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='feature_8_text',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium, magni?', max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='feature_9_text',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium, magni?', max_length=200),
        ),
    ]
