# Generated by Django 2.0.6 on 2018-07-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180713_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='team_member_first',
        ),
        migrations.AddField(
            model_name='content',
            name='team_members',
            field=models.ManyToManyField(to='main.Team'),
        ),
    ]
