# Generated by Django 2.0.6 on 2018-07-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180713_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='team_members',
        ),
    ]
