# Generated by Django 2.0.6 on 2018-07-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_content_team_member_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='team_member_first',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
